import React, {Component} from 'react';

export default class PrivacyPolicy extends Component {
	render () {
		return (
			<div className="container narrow-container">
				<h1 className="text-center">Privacy Policy</h1>
				<p>Below is our privacy policy for information on how we collect, use and disclose personally identifiable information from our users:</p>
				<p>DEVICE USAGE TERMS AND CONDITIONS</p>
				<p>You acknowledge and agree that your use of the Service must also be in accordance with the usage rules established by your mobile device platform or service provider.</p>
				<p>REGISTRATION DATA; ELIGIBILITY</p>
				<p>To access certain areas and features of the Service, you may be required to register with Square One Labs. If you register, you will (i) provide accurate, current and complete information about you as may be prompted by any signup, login and/or registration forms made available via by us (the "Registration Data"); (ii) maintain and promptly update the Registration Data, and any other information you provide to Square One Labs, in order to keep it accurate, current and complete; and (iii) accept all risk of unauthorized access to the Registration Data and any other information you provide to Square One Labs.</p>
				<p>Square One Labs is under no obligation to retain a record of your account or any data or information that you may have stored by means of your account or your use of the Service. You are only authorized to create and use one account for the Service and are prohibited from using alter egos or other disguised identities when using the Service. You are under no obligation to use or continue to use the Service and may stop using the Service without notice to Square One Labs.</p>
				<p>You may not use the Service if you are under 13 years of age (or the age of majority in your jurisdiction).</p>
				<p>GRANT AND RESTRICTIONS</p>
				<p>Subject to the terms, conditions and limitations set forth in these Terms, Square One Labs grants you a non-exclusive, non-transferable and revocable license to use the Application on any mobile device that you own or control. The terms of the license will also govern any upgrades provided by Square One Labs that replace and/or supplement the original Application, unless the upgrade is accompanied by a separate license, in which case the terms of that license will govern.</p>
				<p>You will not do, and will not authorize or permit any third party to do, any of the following: (i) distribute or make the Application available over a network where it could be used by multiple devices at the same time; (ii) rent, lease, lend, sell, redistribute or sublicense the Application; (iii) copy, decompile, reverse engineer, disassemble, attempt to derive the source code of, modify or create derivative works of the Application, any updates or any part thereof (except as and only to the extent any of the foregoing restrictions are prohibited by applicable law) or (iv) remove, alter or obscure any copyright, trademark or other proprietary rights notice on or in the Application. If you violate any of the foregoing restrictions, your right to use of the Application will immediately cease, and you will have infringed the copyright and other rights of Square One Labs, which may subject you to prosecution and damages. Square One Labs reserves all rights not expressly granted to you in these Terms.</p>
				<p>&nbsp;</p>
				<p>RECOMMENDATIONS</p>
				<p>Square One Labs attempts to be as accurate and helpful as possible. Square One Labs may, through the Service, provide offers for local products and services available from third parties. Your business dealings or correspondence with, or participation in promotions of, these third parties, and any terms, conditions, warranties or representations associated with such dealings or promotions, are solely between you and those third parties. Square One Labs makes no guarantee or warranty about any of these services or products, and you agree that Square One Labs will have no liability related to such services or products purchased. If you have reason to believe that a third party product or service you purchased as a result of a recommendation from the Service does not meet your expectations, you must work solely with the third party product or service to resolve your claim. Square One Labs reserves the right, at its sole discretion, to not make a recommendation for a requested product or service.</p>
				<p>Square One Labs may, through the Service, provide assistance with ordering third party services or products when requested via the Service. Square One Labs does not process payment and will send you to the third party vendor or a third party payment processor to collect your payment. Payments processed are governed by the terms of service of the payment processor, not Square One Labs. Charges will include all taxes, including sales tax, excise tax, and value added tax, when applicable. We do not issue Value Added Taxes (VAT) invoices for any purchases made through the Service. We will not book any services or products which include alcohol, adult entertainment, or any other services or products which we deem to be undesirable, in our sole discretion. Square One Labs makes no guarantee or warranty about any of these services or products, and you agree that Square One Labs will have no liability related to such services or products purchased.</p>
				<p>CONSENT TO USE OF DATA AND MOBILE COMMUNICATIONS</p>
				<p>In exchange for Square One Labs providing you with access to the Service, you consent to Square One Labs collecting and using technical data, personal information and related information in connection with your use of the Service, including, but not limited to, contact information and technical information about your device, system, location, and application software, and peripherals, that are gathered periodically to facilitate the features and functionality of the Service and of software updates, product support and other services. You also consent to our communicating with you about the Service.</p>
				<p>COMPATIBILITY WITH MOBILE DEVICES</p>
				<p>Square One Labs does not warrant that the Service will be compatible or interoperable with your mobile device or any other hardware, software or equipment installed on or used in connection with your mobile device.</p>
				<p>CARRIER CHARGES</p>
				<p>The Service requires and uses phone service, data access and text messaging capabilities. Carrier rates for phone, data and text messaging may apply, and you are responsible for all of these charges.</p>
				<p>NO EMERGENCY SERVICES</p>
				<p>The Service is not able to provide any emergency assistance. If you have an emergency, do not use the Service and please call 911.</p>
				<p>ELECTRONIC COMMUNICATIONS</p>
				<p>When you use the Service or send emails to us, you are communicating with us electronically, and you consent to receive communications from us electronically. We will communicate with you by email or providing notices via the Service. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that these communications be in writing. Electronic communications from us, including emails, may include marketing and promotional content.</p>
				<p>THIRD-PARTY INTERACTIONS</p>
				<p>Your use of the Service and your contact, interaction or dealings with any third parties arising out of your use of the Service is solely at your own risk. The recommenders used by Square One Labs are independent contractors and not agents or employees of Square One Labs. Square One Labs is not responsible for, and will not be held liable for, the acts, errors, omissions, representations, warranties, breaches or negligence of any of these recommenders or suppliers for any personal injuries, death, property damage, loss, theft or other damages or expenses resulting therefrom.</p>
				<p>YOUR CONDUCT</p>
				<p>You agree that you are solely responsible for your conduct while using the Service and that you will not do any of the following in connection with the Service:</p>
				<p>Use the Service in any manner that could interfere with, disrupt, negatively affect or inhibit other users from fully enjoying the Service or that could damage, disable, overburden or impair the functioning of the Service in any manner;<br />Harass, threaten, or intimidate Service employees with inappropriate language or behavior;<br />Collect any personally identifiable information about other users (except as specifically authorized by Square One Labs), or intimidate, threaten, stalk or otherwise harass or cause discomfort to other users of the Service;<br />Use the Service for any commercial purpose;<br />Use the Service for any illegal or unauthorized purpose or engage in, encourage or promote any illegal activity or any activity that violates these Terms or any other rules or polices established from time-to-time by Square One Labs;<br />Create an account, post any content, or otherwise use the Service if you are not at least 13 years of age;<br />Modify, adapt, hack, reverse engineer, or emulate the Service;<br />Circumvent or attempt to circumvent any filtering, security measures or other features designed to protect the Service or users of the Service or third- parties; and infringe upon or violate the rights of Square One Labs, our users or any third party.<br />Square One Labs will not be liable for any mistakes, defamation, slander, libel, omissions, falsehoods, obscenity, pornography or profanity you may encounter through the Service. Your use of the Service is at your own risk. Enforcement of the user content and conduct rules set forth in these Terms is solely at Square One Lab's discretion, and failure to enforce such rules in some instances does not constitute a waiver of our right to enforce such rules in other instances. In addition, these rules do not create any private right of action on the part of any third party or any reasonable expectation that the Service will not contain any content that is prohibited by these rules.</p>
				<p>THIRD-PARTY CONTENT</p>
				<p>Square One Labs may provide third-party content via the Service and may provide links to webpages and content of third parties (collectively, &ldquo;Third-Party Content&rdquo;) as a service to those interested in this information. Square One Labs does not control, endorse or adopt any Third-Party Content and makes no representation or warranties of any kind regarding Third-Party Content including, but not limited to, its accuracy or completeness. Square One Labs is not responsible or liable in any manner for any Third-Party Content and undertakes no responsibility to update or review any Third-Party Content. Users use Third-Party Content at their own risk.</p>
				<p>ADVERTISEMENTS AND PROMOTIONS; THIRD-PARTY PRODUCTS AND SERVICES</p>
				<p>Square One Labs may run advertisements and promotions from third parties via the Service or may otherwise provide information about or links to third-party products or services via the Service, in accordance with our privacy policy. Your business dealings or correspondence with, or participation in promotions of, these third parties, and any terms, conditions, warranties or representations associated with such dealings or promotions, are solely between you and those third parties. Square One Labs is not responsible or liable for any loss or damage incurred as the result of any such dealings or promotions or as the result of the presence of non-Square One Labs advertisers or third-party information accessible via the Service.</p>
				<p>TRADEMARKS</p>
				<p>The Square One Labs name and logo are trademarks or registered trademarks of Square One Labs, Inc. in the United States and in various international jurisdictions. These marks may not be reproduced or used without Square One Lab's prior written permission. You may not use any metatags or any other &ldquo;hidden text&rdquo; using &ldquo;Square One Labs&rdquo; or any other name, trademark or product or service name of Square One Labs without our prior written permission. In addition, the look and feel of the Service, including all page headers, custom graphics, button icons and scripts, are the service mark, trademark and/or trade dress of Square One Labs and may not be copied, imitated or used, in whole or in part, without our prior written permission. All other trademarks, registered trademarks, product names and company names or logos made available via the Service are the property of their respective owners.</p>
				<p>OWNERSHIP</p>
				<p>The Service (including, but not limited to, the Application) contains the valuable proprietary content of Square One Labs and our licensors and is protected by copyright and other intellectual property laws and treaties. You will not use the Service (including, but not limited to, the Application) except in its intended manner in accordance with the terms and conditions of these Terms.</p>
				<p>TERMINATION OR MODIFICATION OF APPLICATION</p>
				<p>Square One Labs reserves the right to change, suspend, remove, discontinue or disable access to the Service (including, but not limited to, the Application) at any time without notice. In no event will Square One Labs be liable for the removal of or disabling of access to any portion or feature of the Service (including, but not limited to, the Application).</p>
				<p>TERMINATION</p>
				<p>If you breach any of the terms or conditions of these Terms or Square One Labs discontinues the Application, these Terms will automatically terminate. In the event of the termination of these Terms for any reason, the license granted to you in these Terms will immediately terminate and you must immediately stop all use of the Service (including the Application) and destroy or erase all copies of the Application, if any,in your possession or control. All of the sections of these Terms that by their nature should survive termination will survive any termination of these Terms. For avoidance of doubt, the License section will not survive termination of these Terms. Any use of the Service after termination is unlicensed and is in violation of the copyright and other rights of Square One Labs. Square One Labs and our affiliates reserve the right to refuse service, terminate accounts, remove or edit content or cancel orders in our sole discretion.</p>
				<p>If you wish to terminate this Agreement, you are solely responsible for following proper termination procedures. Simply delete or destroy the copy of the Application that you have downloaded. Cancellation may result in the immediate deletion of any content that you have submitted to Square One Labs. Although your content may not be accessible we may keep such Content for a reasonably commercial time for legal and internal purposes.</p>
				<p>UNLAWFUL ACTIVITY</p>
				<p>We reserve the right to investigate complaints or reported violations of these Terms and to take any action we deem appropriate, including, but not limited to, reporting any suspected unlawful activity to law enforcement officials, regulators or other third parties, and disclosing any information necessary or appropriate to such persons or entities relating to your Registration Data, usage history, location, posted materials, IP addresses and traffic information.</p>
				<p>INFORMATION AND PRESS RELEASES</p>
				<p>The Application may contain information and press releases about us. We disclaim any duty or obligation to update this information. Information about companies other than ours contained in any press release or otherwise should not be relied upon as being provided or endorsed by us.</p>
				<p>DISCLAIMERS</p>
				<p>YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT USE OF THE SERVICE (INCLUDING, BUT NOT LIMITED TO, THE APPLICATION) IS AT YOUR SOLE RISK AND THAT THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, SAFETY, ACCURACY AND EFFORT IS WITH YOU. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICE (INCLUDING, BUT NOT LIMITED TO, THE APPLICATION) IS PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS. SQUARE ONE LABS DISCLAIMS ANY AND ALL WARRANTIES AND REPRESENTATIONS (EXPRESS OR IMPLIED, ORAL OR WRITTEN) WITH RESPECT TO THESE TERMS AND THE SERVICE (INCLUDING, BUT NOT LIMITED TO, THE APPLICATION) WHETHER ALLEGED TO ARISE BY OPERATION OF LAW, BY REASON OF CUSTOM OR USAGE IN THE TRADE, BY COURSE OF DEALING OR OTHERWISE, INCLUDING ANY AND ALL: (I) WARRANTIES OF MERCHANTABILITY; (II) WARRANTIES OF FITNESS OR SUITABILITY FOR ANY PURPOSE (WHETHER OR NOT SQUARE ONE LABS KNOWS, HAS REASON TO KNOW, HAS BEEN ADVISED OR IS OTHERWISE AWARE OF ANY SUCH PURPOSE); AND (III) WARRANTIES OF NON-INFRINGEMENT OR CONDITION OF TITLE. SQUARE ONE LABS DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED IN THE APPLICATION WILL BE ACCURATE OR MEET YOUR REQUIREMENTS, THAT THE OPERATION OF THE APPLICATION WILL BE UNINTERRUPTED OR ERROR-FREE, OR THAT DEFECTS IN THE APPLICATION WILL BE CORRECTED. NO ORAL OR WRITTEN INFORMATION, GUIDELINES OR ADVICE GIVEN BY SQUARE ONE LABS OR OUR AUTHORIZED REPRESENTATIVES WILL CREATE A WARRANTY.</p>
				<p>INDEMNIFICATION</p>
				<p>You will defend, indemnify and hold us, our independent contractors, service providers and consultants, and their respective directors, employees and agents, harmless from and against any and all actual or threatened third-party suits, actions, proceedings (at law or in equity), claims, damages, payments, deficiencies, fines, judgments, settlements, liabilities, losses, costs and expenses (including, but not limited to, reasonable attorney fees, costs, penalties, interest and disbursements) caused by, arising out of, resulting from, attributable to or in any way incidental to (i) your conduct; (ii) your violation of these Terms or your violation of the rights of any third party; or (iii) any User Content you share.</p>
				<p>LIMITATION OF LIABILITY</p>
				<p>IN NO EVENT WILL SQUARE ONE LABS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DIRECT, INCIDENTAL, SPECIAL, INDIRECT, CONSEQUENTIAL, EXEMPLARY OR PUNITIVE DAMAGES WHATSOEVER (INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, BUSINESS, CONTRACTS, REVENUE OR ANTICIPATED SAVINGS; LOSS OR CORRUPTION OF DATA; BUSINESS INTERRUPTION OR ANY OTHER COMMERCIAL DAMAGES OR LOSSES) ARISING OUT OF OR RELATED TO YOUR USE OF OR INABILITY TO USE THE SERVICE (INCLUDING, BUT NOT LIMITED TO, THE APPLICATION), HOWEVER CAUSED, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT, WARRANTY, TORT (INCLUDING NEGLIGENCE, WHETHER ACTIVE, PASSIVE OR IMPUTED), PRODUCT LIABILITY, STRICT LIABILITY OR OTHER THEORY) AND EVEN IF SQUARE ONE LABS HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THIS LIMITATION MAY NOT APPLY TO YOU. IN NO EVENT WILL SQUARE ONE LAB&rsquo;S TOTAL LIABILITY, WHETHER IN CONTRACT, WARRANTY, TORT (INCLUDING NEGLIGENCE, WHETHER ACTIVE, PASSIVE OR IMPUTED), PRODUCT LIABILITY, STRICT LIABILITY OR OTHER THEORY, ARISING OUT OF OR RELATING TO THE USE OF OR INABILITY TO USE THE SERVICE (INCLUDING, BUT NOT LIMITED TO THE APPLICATION) EXCEED $100.00 UNITED STATES DOLLARS.</p>
				<p>COPYRIGHT COMPLAINTS</p>
				<p>If you believe that any material made available via the Service infringes upon any copyright which you own or control, or that any link made available via the Service directs users to material that infringes upon any copyright which you own or control, you may file a notification of such infringement with our Designated Agent as set forth below. Name of Agent Designated to receive notification of claimed infringement: Copyright Agent Full address of Designated Agent to which notification should be sent: XXX Telephone Number of Designated Agent: XXX Facsimile Number of Designated Agent: XXX Email Address of Designated Agent: XXXX See 17 U.S.C. &sect; 512(c)(3) for the requirements of a proper notification. If you knowingly misrepresent in your notification that the material or activity is infringing, you will be liable for any damages including, but not limited to, costs and attorneys' fees, incurred by us or the alleged infringer as the result of our relying upon such misrepresentation in removing or disabling access to the material or activity claimed to be infringing.</p>
				<p>REPEAT INFRINGER POLICY</p>
				<p>In accordance with the Digital Millennium Copyright Act (&ldquo;DMCA&rdquo;) and other applicable law, Square One Labs has adopted a policy of terminating, in appropriate circumstances and at Square One Lab's sole discretion, subscribers or account holders who are deemed to be repeat infringers. Square One Labs may also at our sole discretion limit access to the Service and/or terminate the accounts of any users who infringe any intellectual property rights of others, whether or not there is any repeat infringement.</p>
				<p>APPLICABLE LAW AND VENUE</p>
				<p>The Terms and your use of the Service, including, but not limited to, the Application will be governed by and construed in accordance with the laws of the State of California, applicable to agreements made and to be entirely performed within the State of California, without resort to its conflict of law provisions. In the event of any matter or dispute arising out of or in connection with these Terms, you and Square One Labs will submit to the exclusive jurisdiction of the state and federal courts in the State of California.</p>
				<p>EXPORT LIMITATIONS</p>
				<p>You may not use or otherwise export or re-export the Application except as authorized by United States law and the laws of the jurisdiction in which the Application was obtained. In particular, but without limitation, the Application may not be exported or re-exported into any U.S. embargoed countries or to anyone on the U.S. Treasury Department&rsquo;s list of Specially Designated Nationals or the U.S. Department of Commerce Denied Person&rsquo;s List or Entity List. By using the Application, you represent and warrant that you are not located in any such country or on any such list. You also agree that you will not use the Application for any purposes prohibited by United States law, including, but not limited to, the development, design, manufacture or production of nuclear missiles, or chemical or biological weapons.</p>
				<p>US GOVERNMENT RIGHTS</p>
				<p>The Application and related documentation are &ldquo;Commercial Items,&rdquo; as that term is defined in 48 C.F.R. &sect; 2.101, consisting of &ldquo;Commercial Computer Software&rdquo; and &ldquo;Commercial Computer Software Documentation,&rdquo; as these terms are used in 48 C.F.R. &sect; 12.212 or 48 C.F.R. &sect; 227.7202, as applicable. Consistent with 48 C.F.R. &sect; 12.212 or 48 C.F.R. &sect; 227.7202-1 through &sect; 227.7202-4, as applicable, the Commercial Computer Software and Commercial Computer Software Documentation are being licensed to U.S. Government end users only as Commercial Items and with only those rights as are granted to all other end users pursuant to the terms and conditions herein. Unpublished rights are reserved under the copyright laws of the United States.</p>
				<p>MISCELLANEOUS</p>
				<p>If any part of these Terms is determined to be invalid or unenforceable pursuant to applicable law, including, without limitation, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of these Terms will continue in full effect. Only you and Square One Labs are entitled to enforce these Terms. No third party will be entitled to enforce any of the terms and conditions herein.</p>
				<p>OUR CORPORATE ADDRESS</p>
				<p>Square One Labs, Inc. 3815 Nathan Way, Palo Alto, CA 94303.</p>
				<p>You may also contact our member support team at help@squareonelabs.io</p>
				<p>Security of your Personal Information</p>
				<p>You are responsible for safeguarding and preventing unauthorized access to the user information and password that you use to access the Square One Labs website. You agree not to disclose your password to any third party and you are responsible for any activity using your account, whether or not you authorized that activity. You must immediately notify LawTrades of any unauthorized use of your account.LawTrades endeavors to secure your personal information from unauthorized access, use or disclosure by putting into place physical, electronic and managerial procedures to safeguard the information we collect through this Site. For example, when we collect credit card information, we use a secure server with Secure Socket Layer (SSL) encryption software and store such credit card information using encryption methods designed to prevent unauthorized access. Additionally, your account information is accessible online only through the use of a password.</p>
				<p>Children Under Thirteen</p>
				<p>Square One Labs does not knowingly collect personally identifiable information from children under the age of thirteen. If you are under the age of thirteen, you must ask your parent or guardian for permission to use this website.</p>
			</div>
		);
	}
}